# Generated by Django 4.1.2 on 2022-10-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=200, verbose_name="foreign")),
                (
                    "description",
                    models.CharField(default="", max_length=200, verbose_name="native"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("AUDIO", "Audio"),
                            ("VIDEO", "Video"),
                            ("IMAGE", "Image"),
                        ],
                        default="IMAGE",
                        max_length=200,
                    ),
                ),
                ("path_to_file", models.FileField(blank=True, upload_to="word/")),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="polls.word",
                    ),
                ),
            ],
        ),
    ]
